Repository Julenrp/decide-part-camaron-1, pull requests merged in 2023-12, with the labels that each got.

#24 TASK-009-Test de registro de usuarios Fixes #3 #15
  decide/authentication/tests.py
  decide/authentication/urls.py
Labels: 🔨 creation, 🔧 test

#25 TASK-017-Exportar censo en diferentes formatos #22 #23
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
Labels: 🔨 creation, ☑ task, 🔧 test

#43 TASK-020-CAMBIO EN .YML PARA QUE ENVÍE NOTIFICACIÓN AL DISCORD #42
  .github/workflows/discord.yml
Labels: 🔨 creation, ☑ task, 💻 integration

#45 TASK-021-Añadir a develop2 todas las funcionalidades arregladas de nuevo
  .github/workflows/django.yml
  decide/base/templates/home.html
  decide/census/templates/census/census_list.html
  decide/census/templates/census/results.html
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  decide/store/tests.py
  decide/voting/tests.py
Labels: 🔨 creation

#49 Feat Vizualizar Votos:
  decide/census/forms.py
  decide/inicio/templates/inicio/base.html
  decide/visualizer/templates/visualizer/verVoto.html
  decide/visualizer/urls.py
  decide/visualizer/views.py
Labels: 🔨 creation

#50 Integrar Visualizar Votaciones Abiertas
  decide/census/forms.py
  decide/inicio/templates/inicio/base.html
  decide/visualizer/templates/visualizer/verVoto.html
  decide/visualizer/urls.py
  decide/visualizer/views.py
Labels: 💻 integration
